### ISSUE TITLE
[cloudflared] Enabling metrics causes "Incorrect Usage: flag provided but not defined: -metrics"

### ISSUE THREAD

**Issue by joscha-alisch** [kubitodev/helm#20]
After enabling the prometheus metrics support from #19 , the pod can't succesfully start up anymore with error message

```
Incorrect Usage: flag provided but not defined: -metrics
```

This happens because `--metrics` is placed after the subcommand `run` in the container command, when cloudflared requires it to be placed after the main command `tunnel`.

The following is wrong:
```
cloudflared tunnel run --metrics 0.0.0.0:8080
```

while the following is correct:

```
cloudflared tunnel --metrics 0.0.0.0:8080 run 
```

I'll send a PR to fix this.

**Comment by nushkovg** [comment]
Fixed in #22.
