### ISSUE TITLE
Outline 1.0.6: Helm render error from wrong indent on ingress paths list

### ISSUE THREAD

**Issue by Lunatunny** [kubitodev/helm#29]
It's just a minor issue but it prevents the helm chart from rendering if you enable ingresses.

How it is right now.
![image](https://github.com/user-attachments/assets/5506c926-b220-497e-9246-9c238c4e9010)

Error since 003-ingress.yaml attempts to unwrap "paths" as a list, not a list item.
![image](https://github.com/user-attachments/assets/286258f9-3452-4289-a244-d83e4024eeab)

Fix
![image](https://github.com/user-attachments/assets/231ea4de-bd35-486c-a235-f2120b6d3981)

**Comment by nushkovg** [comment]
Fixed in the latest `1.1.0` release.
