### ISSUE TITLE
Bazarr media volume condition issue

### ISSUE THREAD

**Issue by Omripresent** [kubitodev/helm#31]
Under the Servarr chart the Bazarr deployment volume mount is referencing jellyfin media PVC regardless if it's enabled or not here:
 https://github.com/kubitodev/helm/blob/f4429b260729b92cf9c7b1d5cfd57dd70d77efb0/charts/servarr/templates/bazarr/deployment.yaml#L53
 compared to Radarr:
 https://github.com/kubitodev/helm/blob/f4429b260729b92cf9c7b1d5cfd57dd70d77efb0/charts/servarr/templates/radarr/deployment.yaml#L61
 or Sonarr:
 https://github.com/kubitodev/helm/blob/f4429b260729b92cf9c7b1d5cfd57dd70d77efb0/charts/servarr/templates/sonarr/deployment.yaml#L61

**Comment by nushkovg** [comment]
Thank you for noticing that! Fixed in release `1.0.5`.
