### ISSUE TITLE
Similar to issue #31 for prowlarr

### ISSUE THREAD

**Issue by Omripresent** [kubitodev/helm#32]
The PVC condition doesn't account for the state of jellyfin here similar to issue #31 :
https://github.com/kubitodev/helm/blob/29dc0ef1feaeca4aad943a932122d6740cb43a65/charts/servarr/templates/prowlarr/deployment.yaml#L53C31-L57C24

**Comment by nushkovg** [comment]
Thank you again, fixed in `1.0.6`!
